import About from '@components/About'
import Presentation from '@components/Presentation'
import Proyects from '@components/Proyects'
import Grid from '@components/ui/Grid'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>DanielCG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid>
        <Presentation />
        <About />
        <Proyects />
      </Grid>
    </>
  )
}
